services:
  # 1. Base de Datos MySQL
  mysql_db:
    image: mysql:8.0
    container_name: taskflow_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: GestorProyectos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  # 2. Tu API (Backend) - Proyecto PruebaApi
  api_backend:
    build:
      context: ../PruebaApi # La carpeta de tu API
      dockerfile: Dockerfile
    container_name: taskflow_api
    ports:
      - "8083:8083"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/GestorProyectos?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123

  # 3. Tu Web (Frontend) - Proyecto proyectoDef2
  web_frontend:
    build:
      context: . # La carpeta actual (proyectoDef2)
      dockerfile: Dockerfile
    container_name: taskflow_web
    ports:
      - "8081:8080" # Usamos 8081 en tu m√°quina para evitar conflictos
    depends_on:
      - api_backend
    environment:
      API_URL: http://api_backend:8083

volumes:
  mysql_data: